### ISSUE TITLE
If analyze is run after intro markers are deleted do they get regenerated?

### ISSUE THREAD

**Issue by albino1** [danrahn/IntroEditorForPlex#3]
I was wondering if you use this tool to delete the intro markers for a series if the markers are regenerated if you intentionally run Analyze on the series, or maybe generated automatically when the Scheduled Tasks run overnight if you have Intro Detection enabled.  If not, then is the only way to get intro markers back to then manually add them with this tool? Thanks.

**Comment by danrahn** [comment]
While I don't know if it will be picked up during scheduled tasks, if you delete automatically generated markers, Plex will regenerate them if you analyze the season.

**Comment by albino1** [comment]
Perfect.  I'm definitely going to give this tool a try, thanks for making it!

**Comment by matthew10199** [comment]
@danrahn I've tried deleting the markers, confirmed it worked by checking the XML for an episode, then analyzing the season to regenerate the markers. However when I do the intro detection finishes almost instantly and results in the same intro markers that I had before deleting, rather than regenerating them. Do you know why this might be happening?

**Comment by danrahn** [comment]
@MossyGreen I think Plex also stores the underlying analysis data so it doesn't have to regenerate it for every episode when a new one is added to the season. I haven't done any actual testing, but it looks like that's stored in the blobs database, where `blob_type` is `5`. To remove those, you could run this against the blobs database using [Plex SQLite](https://support.plex.tv/articles/repair-a-corrupted-database/#toc-0):

```sql
DELETE FROM blobs WHERE blob_type=5;
```


As I said though, I haven't done any actual testing of that (and don't have the free time to look into adding it as a feature in this tool), so definitely make sure everything is backed up first.

**Comment by albino1** [comment]
Now that many markers are [cloud based](https://support.plex.tv/articles/credits-detection/), could there be a situation where the initial out of sync marker was sent to the cloud, then when you delete and reanalyze the file it finds an immediate match and just downloads the out of sync marker from the cloud again?

**Comment by MossyGreen** [comment]
I tried setting the "Marker Source" to "local only" so that it wouldn't pull from the cloud, however it still completed intro detection immediately, so I'm guessing the issue lies with the stored analysis data. I went ahead and deleted the show and added it back in and sure enough it regenerated (even with "Marker Source" set to "both").

There was (is?) an issue with Plex where when replacing existing shows it does not reanalyze the intros. I didn't realize it was happening for quite a long time so I have many shows out of sync and try to fix them when I find them. It's a shame as this was the main reason I wanted to use the intro editor, to save me the trouble of having to delete/re-add everything, which moves existing shows back into recently added as well as regenerating the video preview thumbnails.

I never tried deleting from the blobs database, that may be a solution too. I might try that and just regenerate the intros for my entire library one of these days. I'll post an update here if I ever try it.

**Comment by MossyGreen** [comment]
I got around to testing it: deleting the blobs like you recommended worked! After executing the command (which took a little time to figure out how to do in docker) and deleting the markers again the intros generated from scratch. Thanks so much for the advice!
