### ISSUE TITLE
Button to pruge all intro marker for a selected library

### ISSUE THREAD

**Issue by Skaronator** [danrahn/IntroEditorForPlex#4]
First: Thanks for your work and making it available for everyone!

It would be great to have a button to pruge all intro marker for a selected library. My usecase would be to re-create all detected intros by plex. My library is really old and Plex got a bit better at detecting intros since the first release and I would like to re-detect all intros.

**Comment by danrahn** [comment]
Definitely something I can look into. I unfortunately haven't had a ton of time to work on this lately, but it shouldn't be too difficult to implement. If you don't want to wait for a UI option and are comfortable [running SQL directly against your database](https://support.plex.tv/articles/repair-a-corrupted-database/), running the following should work, where `LIBRARY_ID` is the id of the library you want to remove all markers for (you can use the `--list` command from the [command line scanner](https://support.plex.tv/articles/201242707-plex-media-scanner-via-command-line/) to find the id):

```SQL
DELETE FROM taggings
WHERE taggings.id IN (
	SELECT t.id AS id FROM taggings t
	INNER JOIN tags ON tags.id=t.tag_id
	INNER JOIN metadata_items ON metadata_items.id=t.metadata_item_id
	WHERE tags.tag_type=12 AND metadata_items.library_section_id=LIBRARY_ID
);
```

I'd definitely recommend shutting down PMS and backing up your db before trying it though.

**Comment by albino1** [comment]
Since you seem to be on a run of improvements (thanks!) I was wondering if maybe you would be interested in revisiting this enhancement.  I'm in a similar boat where I would really like to wipe all of the markers from a particular library and start fresh without potentially destroying my database with my clumsy fingers, hah.

Though, I did see Plex say that community generated cloud markers (like the movie markers) are coming to TV soon, so it might be worth holding off actually doing anything until that rolls out as the analysis after a purge would likely be significantly faster.

**Comment by danrahn** [comment]
Yes, I can look into this ~soon. One potential issue that I haven't looked into at all is that Plex might be caching the markers somewhere else in addition to the database (e.g. the XML files it also generates in the data directory). I've noticed that when I wipe out markers for a given episode and then reanalyze it season, the markers are added ~instantly instead of the usual wait for Plex to actually analyze the the files. If that's the case, it might not be as valuable to add to this application, though it may still be useful to have a way to "start fresh" with a section.

**Comment by albino1** [comment]
I think I've noticed this in the past, and the only way I could get the markers to successfully purge from a season and actually re-scan properly was to do a full Plex Dance.  So yeah, maybe they're stored somewhere else as well, I'm not sure.

**Comment by danrahn** [comment]
The [latest beta](https://github.com/danrahn/IntroEditorForPlex/releases/tag/v2.2.0-beta) attempts to address this, giving you the option to completely remove all markers for a given library (both user- and Plex-generated). It might still run into the issue described above if your goal is to completely start the generation from scratch, but it will at least get you one step closer.

**Comment by danrahn** [comment]
Closing as this is now in the non-beta release [v2.2.0](https://github.com/danrahn/IntroEditorForPlex/releases/tag/v2.2.0).
