### ISSUE TITLE
Instruction, for installation on Raspberry Pi - Raspberry OS

### ISSUE THREAD

**Issue by kaitokid187** [danrahn/IntroEditorForPlex#5]
Unfortunately I am not so proficient with English and programming languages. would a tutorial be possible.?

I have a Plex server running on a Raspberry Pi 4 under Raspberry OS.
How to install and use your application under Raspbarry Pi?!

or ...

under Windows via network access?!

Thanks

Translate form DeepL.com

**Comment by danrahn** [comment]
Unfortunately I've never worked with any type of Raspberry Pi, so can't offer much advice outside of the general instructions in the [wiki](https://github.com/danrahn/IntroEditorForPlex/wiki).

As far as Windows via network access, that could be possible, though preview thumbnails likely wouldn't work. If the database can be accessed from your Windows PC, you could [download the editor executable](https://github.com/danrahn/IntroEditorForPlex/releases), and during the [initial setup](https://github.com/danrahn/IntroEditorForPlex/wiki/configuration#first-run), in the database path enter the network path to your Plex database (make sure Plex isn't running, and you may also have to give a "fake", but real path for Plex data directory path). When it asks you if you want to enabled preview thumbnails, make sure you disable them, otherwise the application will complain about the data directory not existing.
